<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/**
 * @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

echo $this->getUrl('reusableimages/product/usegallery');
?>

<div class="row">
    <div class="add-video-button-container">
        <button id="add_video_button"
                title="<?= $block->escapeHtmlAttr(__('Ditto Product Gallery')) ?>"
                data-role="add-video-button"
                type="button"
                class="action-secondary"
                data-ui-id="widget-button-1">
            <span><?= $block->escapeHtml(__('Ditto Product Gallery')) ?></span>
        </button>
    </div>
</div>
